[tool.poetry]
name = "doc-converter"
version = "v1.4.2"
description = "A library to convert them all. Get text and metadata from document types like pdf and html."
authors = ["Magnus Finkenzeller <magnus.finkenzeller@neomo.com>"]
readme = "README.md"
packages = [
    { include = "doc-converter" },
]

[[tool.poetry.source]]
name = "pytorch_cpu"
url = "https://download.pytorch.org/whl/cpu"
priority = "explicit"


[tool.poetry.dependencies]
python = ">=3.12,<3.13"
torch = { version = "2.11.0", source = "pytorch_cpu" }
torchvision = { version = "0.26.0", source = "pytorch_cpu" }
docling = "2.88.0"
easyocr = "1.7.2"
beautifulsoup4 = "^4.12.3"
newspaper3k = "^0.2.8"
regex = "*"
lxml = "4.9.3"

[tool.poetry.group.dev.dependencies]
pytest = "*"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
